### ISSUE TITLE
whats the point of this archive?

### ISSUE THREAD

**Issue by radmanplays** [Eagler-Archive/.github#1]
this archive is just a archive that forks repos from other archives so whats the point of making it? 
also if the repos from the other archives get dmca'd all forks get deleted so this archive is useless

**Comment by Coll147** [comment]
Yes, I recently realized that. That's why create separate repositories. And the idea of this is simply to try to save the different eaglercraft clients

**Comment by btplayzxgit** [comment]
thats why is suggested to rename it to "EaglerStorage"
